<?php

return [
    [
        'jenis_produksi' => 'GCGU/ GCBU',
        'rajutan_lusi' => '11,65',
        'lebar_kain' => '120X3',
        'jumlah_benang' => '1724',
        'lebar_benang' => '2,4',
        'denier' => '900',
        'beam_isi' => '',
        'beam_sisa' => '',
        'berat' => '',
    ],
    [
        'jenis_produksi' => 'Wistaria',
        'rajutan_lusi' => '11,65',
        'lebar_kain' => '120X3',
        'jumlah_benang' => '1856',
        'lebar_benang' => '2,8',
        'denier' => '900',
        'beam_isi' => '',
        'beam_sisa' => '',
        'berat' => '',
    ],
    [
        'jenis_produksi' => 'UVS',
        'rajutan_lusi' => '9,77',
        'lebar_kain' => '340',
        'jumlah_benang' => '1406',
        'lebar_benang' => '1,5',
        'denier' => '500',
        'beam_isi' => '',
        'beam_sisa' => '',
        'berat' => '',
    ],
    [
        'jenis_produksi' => 'Natalia Phinisi (rajutan 12)',
        'rajutan_lusi' => '11,65',
        'lebar_kain' => '125X3',
        'jumlah_benang' => '1857',
        'lebar_benang' => '2,8',
        'denier' => '900',
        'beam_isi' => '',
        'beam_sisa' => '',
        'berat' => '',
    ],
    [
        'jenis_produksi' => 'CWU',
        'rajutan_lusi' => '14,00',
        'lebar_kain' => '125X3',
        'jumlah_benang' => '2137',
        'lebar_benang' => '2,8',
        'denier' => '1000',
        'beam_isi' => '',
        'beam_sisa' => '',
        'berat' => '',
    ]
];
